### ISSUE TITLE
kube-sonobuoy panics if it cannot connect to the API server

### ISSUE THREAD

**Issue by alexbrand** [heptio/sonobuoy#257]
In the case that sonobuoy fails to connect to the API server during startup, the process crashes due to a panic. There is no forward progress that could be made in this case, as we are unable to talk to the API server, but I wonder if the error could be handled more gracefully.

```
$ kubectl logs -n heptio-sonobuoy sonobuoy kube-sonobuoy
time="2018-02-15T19:50:17Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2018-02-15T19:50:17Z" level=info msg="unknown template type" filename=..2982_16_02_04_49_46.880772909
time="2018-02-15T19:50:17Z" level=info msg="unknown template type" filename=..data
time="2018-02-15T19:50:17Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2018-02-15T19:50:17Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2018-02-15T19:50:17Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2018-02-15T19:50:17Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2018-02-15T19:50:17Z" level=info msg="Loading plugin driver Job"
time="2018-02-15T19:50:17Z" level=info msg="Filtering namespaces based on the following regex:.*|heptio-sonobuoy"
panic: Get https://10.96.0.1:443/api/v1/namespaces: dial tcp 10.96.0.1:443: getsockopt: no route to host
goroutine 1 [running]:
github.com/heptio/sonobuoy/pkg/discovery.FilterNamespaces(0x18ce0c0, 0xc420206f70, 0xc42038a120, 0x12, 0x1, 0xc42038a120, 0x12)
	/go/src/github.com/heptio/sonobuoy/pkg/discovery/utils.go:44 +0x480
github.com/heptio/sonobuoy/pkg/discovery.Run(0x18ce0c0, 0xc420206f70, 0xc4201028c0, 0x0)
	/go/src/github.com/heptio/sonobuoy/pkg/discovery/discovery.go:77 +0x5c4
github.com/heptio/sonobuoy/cmd/sonobuoy/app.runMaster(0xc4204c26c0, 0xc4204314a0, 0x0, 0x3)
	/go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/app/master.go:63 +0x7c
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204c26c0, 0xc420431380, 0x3, 0x3, 0xc4204c26c0, 0xc420431380)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19174c0, 0x1, 0x1917940, 0x1917b80)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:729 +0x2fe
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).Execute(0x19174c0, 0xc42034bf70, 0xf3ecd4)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
	/go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/main.go:25 +0x2d
```

**Comment by alexbrand** [comment]
I am looking into the code to see where/what needs to change if we decide to improve this.

**Comment by timothysc** [comment]
It's done on purpose.  If it can't talk with the api-server all bets are off. 

Fail-Fast mantra on distributed systems.

**Comment by chuckha** [comment]
We could probably do something a little more robust than panic. Initiate shutdown perhaps

**Comment by timothysc** [comment]
Exiting is also ok with me, but trying to reconnect to recover is not.  

Sonobuoy's purpose is to identify issues on a deployment and exposing these types of failures, in the beginning, is a good thing.

**Comment by alexbrand** [comment]
Yeah, we can't do anything if we can't talk to the API server. But maybe there is something to do from a UX perspective: improved error message or something.
