### ISSUE TITLE
segfault when attempting to run e2e command

### ISSUE THREAD

**Issue by waynr** [heptio/sonobuoy#504]
**What steps did you take and what happened:**
```
wayne@7aeaa1da89bc:/k8s-installer$ sonobuoy e2e --show failed --kubeconfig clusters/kubernetes-wwarren-test/generated/auth/kubeconfig --kube-conformance-image-version v1.10 /testdata/201807231951_sonobuoy_8ba9f131-21db-4355-aae1-56bb6c69c63c.tar.gz
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xde0a06]

goroutine 1 [running]:
github.com/heptio/sonobuoy/vendor/k8s.io/client-go/rest.CopyConfig(0x0, 0x0)
        /go/src/github.com/heptio/sonobuoy/vendor/k8s.io/client-go/rest/config.go:425 +0x36
github.com/heptio/sonobuoy/vendor/k8s.io/client-go/dynamic.NewForConfig(0x0, 0x0, 0x0, 0x0, 0x42a3c0)
        /go/src/github.com/heptio/sonobuoy/vendor/k8s.io/client-go/dynamic/simple.go:40 +0x2f
github.com/heptio/sonobuoy/pkg/dynamic.NewAPIHelperFromRESTConfig(0x0, 0xc42008dbc0, 0x429ed9, 0xc4200d0620)
        /go/src/github.com/heptio/sonobuoy/pkg/dynamic/client.go:37 +0x2f
github.com/heptio/sonobuoy/cmd/sonobuoy/app.getSonobuoyClient(0x0, 0x1354080, 0xc420126000, 0x0)
        /go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/app/common.go:12 +0x2f
github.com/heptio/sonobuoy/cmd/sonobuoy/app.e2es(0xc4200fcc80, 0xc4203f9260, 0x1, 0x7)
        /go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/app/e2e.go:89 +0x153
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200fcc80, 0xc4203f91f0, 0x7, 0x7, 0xc4200fcc80, 0xc4203f91f0)
        /go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1b6d0e0, 0x0, 0xc, 0x1c)
        /go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).Execute(0x1b6d0e0, 0xc42008df78, 0xc4200b6058)
        /go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /go/src/github.com/heptio/sonobuoy/main.go:27 +0x2d
```

**What did you expect to happen:**
I expected either an error message or some useful display of the e2e test results. Did not expect a segfault.

**Anything else you would like to add:**
This is as deep as I got into the stacktrace: https://github.com/heptio/sonobuoy/blob/0470e243ea524d21fb3b9cdd46df02cc6d0ab72d/cmd/sonobuoy/app/e2e.go#L89

**Environment:**
The only thing that seems to be relevant here is:
- Sonobuoy version: `v0.11.4`

**Comment by timothysc** [comment]
This is fixed on master.  

If you run `go get -u -v github.com/heptio/sonobuoy` it will pull in the fix.

**Comment by timothysc** [comment]
xref: https://github.com/heptio/sonobuoy/pull/500
